### ISSUE TITLE
Question: How do I spin up multiple instances of the same service?

### ISSUE THREAD

**Issue by bad5ect0r** [yeswehack/pwn-machine#3]
Is there a recommended way to have multiple instances of the same service using pwn-machine? My objective is to get different ezXSS instances under different subdomains.

My config.yml file looks like this:

### config.yml

```yaml
...
services:
  traefik: {}
  dns: {}
  ezxss:
    https:
      domains:
        - x.xxx.com'
```

The docker-compose.yml file of ezXSS looks like this:

### docker-compose.yml

```yaml
version: '3.7'

services:
  phpapache:
    build: ./php
    depends_on:
      - mysql
    volumes:
      - ezxss:/var/www/html
    labels:
      - "pm.http.port=80"
    networks:
      - traefik
      - ezxss
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ezxss
    networks:
      - ezxss

networks:
  ezxss:

volumes:
  ezxss:
    name: ezxss
```

Now, I'm happy to add multiple lines of the service definition in the config.yml file, but is there a way to pass variables down using config.yml to have them be referenced in the docker-compose.yml file and maybe somewhere else? Because right now, I would need to copy the ezXSS folder in the services multiple times changing the volume name, network name, etc. It would be nice to just change a single value in a new line in the config.yml file and have that value replicated in the docker-config.yml file.

**Comment by B-i-t-K** [comment]
There is no way to do it via pwn-machine right now, But you can probably achieve your goal by setting up all the traefik labels in your docker-compose yourself. 
Like always, if you find a good config syntax, I would love to add this to pwn-machine.

**Comment by SakiiR** [comment]
If you want multiple ezxss instances you can do that right ? 

```yaml
...
services:
  traefik: {}
  dns: {}
  ezxss1:
    https:
      domains:
        - ez1.xxx.com'
  ezxss2:
    https:
      domains:
        - ez2.xxx.com'
```

I might be wrong on this, but this seems fair to me.

Is it going to use the same volume each time ?

**Comment by bad5ect0r** [comment]
@SakiiR, No it won't. That's fine if this is the only way to do this right now. It would be cool to see a feature that passes variables from the config.yml file to the docker-compose.yml file.

**Comment by SakiiR** [comment]
@B-i-t-K what if we add something like passing extra objects to the docker-compose associated services ?

**Comment by bad5ect0r** [comment]
@SakiiR, then I might be able to do something like 

### config.yml

```yaml
services:
  traefik: {}
  dns: {}
  ezxss1:
    https:
      domains:
        - 'x.xxx.com'
    vars:
      network:
        - 'ezxss1'
  ezxss2:
    https:
      domains:
        - 'y.xxx.com'
    vars:
      network:
        - 'ezxss2'
```

### docker-compose.yml

```yaml
version: '3.7'

services:
  phpapache:
    build: ./php
    depends_on:
      - mysql
    labels:
      - "pm.http.port=80"
    networks:
      - traefik
      - ezxss
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ezxss
    networks:
      - ${network}

networks:
  ${network}:
```
