### ISSUE TITLE
Question: What is the best way to copy files from the local machine to a volume when starting a service?

### ISSUE THREAD

**Issue by bad5ect0r** [yeswehack/pwn-machine#4]
Since we are using named volumes, we need to manually copy files that we want in the volume by mounting it and copying it. Is there a better way?

**Comment by B-i-t-K** [comment]
Do you have an example ?

**Comment by bad5ect0r** [comment]
For [ezXSS](https://github.com/hack2012/xssblind) we need to copy the www folder into the /var/www/html folder in the php container. But for pwn-machine, I've used a named volume in the docker-compose.yml file:

### docker-compose.yml

```yaml
version: '3.7'

services:
  phpapache:
    build: ./php
    depends_on:
      - mysql
    volumes:
      - ezxss:/var/www/html
    labels:
      - "pm.http.port=80"
    networks:
      - traefik
      - ezxss
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ezxss
    networks:
      - ezxss

networks:
  ezxss:

volumes:
  ezxss:
    name: ezxss
```
The result is an empty /var/www/html directory in the container.

**Comment by B-i-t-K** [comment]
The problem with volume while using docker-machine is that the local path refer to your host and not your local computer.
For ezXSS I use the following Dockerfile. This way the data is copied inside the container during the build.

```dockerfile
FROM php:7-apache
RUN a2enmod headers
RUN a2enmod rewrite
RUN docker-php-ext-install pdo pdo_mysql
COPY . ./
```

And my docker-compose is very similar:

```yaml
version: "3.7"

services:
  ezxss:
    build: .
    labels:
      - "pm.http.port=80"
    networks:
      - traefik
      - ezxss
  ezxss-db:
    image: mysql
    networks:
      - ezxss
    environment:
      MYSQL_DATABASE: 'ezxss'
      MYSQL_USER: 'ezxss'
      MYSQL_PASSWORD: 'ezxss'
      MYSQL_ROOT_PASSWORD: 'ezxss'
    volumes:
      - ezxss-db:/var/lib/mysql



networks:
  ezxss:

volumes:
  ezxss-db:
    name: ezxss

```
