### ISSUE TITLE
Docker Compose .env Variables Blank

### ISSUE THREAD

**Issue by bad5ect0r** [yeswehack/pwn-machine#7]
I use the [.env variables for docker-compose](https://docs.docker.com/compose/env-file/). It works fine when doing `docker-compose up` locally but when doing `pm service build`, it is blank.

```
[I] (venv) ✔︎ webhawk (master) ✗ pm service build webhawk
The DJANGO_SUPERUSER_PASSWORD variable is not set. Defaulting to a blank string.
...
```

_docker-compose.yml_
```
version: '3.7'

services:
    webhawk-webhawk:
        build:
            context: .
            args:
                DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
        container_name: webhawk
        volumes:
            - static_volume:/static
        expose:
            - 8000
        networks:
            - webhawk
    webhawk-nginx:
        build: ./nginx
        container_name: nginx
        labels:
            - "pm.http.port=80"
        volumes:
            - static_volume:/static
        depends_on:
            - webhawk-webhawk
        networks:
            - webhawk
            - traefik

volumes:
    static_volume:

networks:
    webhawk:
```

_.env_

```
[I] (venv) ✔︎ webhawk (master) ✗ cat .env
...
DJANGO_SUPERUSER_PASSWORD=change_me
```
